VIEWS = []


# example dashboard view
VIEWS.append( 
    {
        "id": "example_data_collector", 
        "title": "Example Dashboard",
        "icon": "target",
        #"default_event_name_param": "example_event",
        #"event_name_param_choices": [{"value": "example_event", "label": "Example Event"}, {"value": "another_example_event", "label": "Another Example Event"}],
        #"event_name_param_label": "Select example event to show:",
        "show_page_time_aggregation_selection": False,
        "inline_description": "An example dashboard to display a graph of randomly generated data.",
        "long_description": "This dashboard shows the events generated by the 'example_data_collector' on a simple line graph.", 
        "data": [
            {
                "id": "example_events", 
                "event": "example_event", 
                "max_age_days": 10, 
                "tags": None
            }
        ],
        "widgets": [
            # example widget: lines graph on the example_events data source
            {
                "title": "Example Data Collector Graph",
                "description": "A graph showing the events collected by the example data collector.",
                "data_sources": ["example_events"],
                "columns": 12,
                "type": "line_graph",
                "time_range_filter": True
            },
            # example widget: free html box
            {
                "title": "HTML Box",
                "description": "This widget allow you to embed any HTML content.",
                "data_sources": [],
                "columns": 6,
                "height": 1,
                "type": "html_box",
                "html_content": """<div class="container"><div class="p-3 mb-2 bg-primary text-white">This box is generated from free HTML in view config file.</div></div>"""
            },
            # example widget: pie chart on the example_events data source
            {
                "title": "Example Data Collector Pie Chart",
                "description": "A pie chart showing the distribution of values collected by the example data collector.",
                "data_sources": [{"id": "example_events", "tags": ["type_a"]}, {"id": "example_events", "tags": ["type_b"]}],
                "type": "pie_chart",
                "columns": 6,
                "height": 1,
                "style": {
                    "donut": True,
                    "show_center_text": True,
                    "center_text_formatter": "{total} Events",
                    "center_text_size": 16,
                    "aggregation_type": "sum",
                    "radius": "70%",
                    "show_legend": True,
                }
            }
        ]
    }
)

# system monitor dashboard view
VIEWS.append(
    {
        "id": "system_monitor", 
        "title": "System Monitor",
        "icon": "line_chart_up",
        "long_description": "This dashboard display system metrics such as CPU, memory, disk, and network usage.",
        "inline_description": "This dashboard shows system metrics.", 
        "default_time_aggregation": "disabled",
        "data": [
            {
                "id": "cpu_usage", 
                "event": "cpu_usage", 
                "max_age_days": 14, 
                "tags": None
            },
            {
                "id": "memory_usage_mb", 
                "event": "memory_usage_mb", 
                "max_age_days": 14, 
                "tags": None
            },
            {
                "id": "memory_usage_percent", 
                "event": "memory_usage_percent", 
                "max_age_days": 14, 
                "tags": None
            },
            {
                "id": "network_usage_bytes_sent", 
                "event": "network_usage_bytes_sent_per_sec", 
                "max_age_days": 14, 
                "tags": None
            },
            {
                "id": "network_usage_bytes_recv", 
                "event": "network_usage_bytes_recv_per_sec", 
                "max_age_days": 14, 
                "tags": None
            },
            {
                "id": "disk_usage_percent", 
                "event": "disk_usage_percent", 
                "max_age_days": 14, 
                "tags": None
            },
            {
                "id": "disk_usage_mb", 
                "event": "disk_usage_used_mb", 
                "max_age_days": 14, 
                "tags": None
            },
            {
                "id": "io_write_bytes_per_sec", 
                "event": "io_operations_write_bytes_per_sec", 
                "max_age_days": 14, 
                "tags": None
            },
            {
                "id": "io_read_bytes_per_sec", 
                "event": "io_operations_read_bytes_per_sec", 
                "max_age_days": 14, 
                "tags": None
            },
            {
                "id": "processes_count", 
                "event": "processes_count", 
                "max_age_days": 14, 
                "tags": None
            }
        ],
        "widgets": [
            {
                "title": "CPU Usage Health",
                "description": "Last measurement CPU utilization",
                "data_sources": ["cpu_usage"],
                "type": "gauge",
                "aggregation_type": "last",
                "columns": 4,
                "height": 0.7,
                "show_last_value_time": True,
                "style": {
                    "min": 0,
                    "max": 100,
                    "gauge_color": "primary",           # Used when useDynamicColors is False
                    "value_formatter": "{value}%",
                    "axis_colors": [
                        [70, "success"],     # 0-70%: green (good)
                        [90, "warning"],     # 70-90%: yellow (warning)
                        [100, "danger"]      # 90-100%: red (critical)
                    ],
                    "useDynamicColors": True,           # True = colors match axis zones, False = use gauge_color
                    "show_progress": True,
                    "radius": "75%",
                    "label": "CPU %"
                }
            },
            {
                "title": "Memory Usage Health",
                "description": "Last measurement memory utilization",
                "data_sources": ["memory_usage_percent"],
                "type": "gauge",
                "aggregation_type": "last",
                "columns": 4,
                "height": 0.7,
                "show_last_value_time": True,
                "style": {
                    "min": 0,
                    "max": 100,
                    "gauge_color": "primary",
                    "value_formatter": "{value}%",
                    "axis_colors": [
                        [70, "success"],     # 0-70%: green (good)
                        [90, "warning"],     # 70-90%: yellow (warning)
                        [100, "danger"]      # 90-100%: red (critical)
                    ],
                    "show_progress": True,
                    "radius": "75%",
                    "label": "Memory %"
                }
            },
            {
                "title": "Disk Usage Health",
                "description": "Last measurement disk utilization",
                "data_sources": ["disk_usage_percent"],
                "type": "gauge",
                "aggregation_type": "last",
                "columns": 4,
                "height": 0.7,
                "show_last_value_time": True,
                "style": {
                    "min": 0,
                    "max": 100,
                    "gauge_color": "primary",
                    "value_formatter": "{value}%",
                    "axis_colors": [
                        [70, "success"],     # 0-70%: green (good)
                        [90, "warning"],     # 70-90%: yellow (warning)
                        [100, "danger"]      # 90-100%: red (critical)
                    ],
                    "show_progress": True,
                    "radius": "75%",
                    "label": "Disk %"
                }
            },
            {
                "title": "CPU Usage - Percent",
                "description": "A graph showing the CPU usage over time.",
                "data_sources": ["cpu_usage"],
                "type": "line_graph",
                "values_suffix": "%",
                "columns": 7,
                "time_aggregation": {
                    "starting_value": "page_default",
                    "allow_selection": True,
                    "aggregation_function": "average_round"
                },
                "style": {
                    "lines_smooth": False,
                    "area_fill": True,
                    "lines_color": 0,
                    "label": "CPU Usage",
                    "markline": { "value_y": 80, "style": "dashed", "color": "red" }
                },
                "time_range_filter": True
            },
            {
                "title": "IO Read/Writes - Bytes",
                "description": "A graph showing the IO read/write bytes over time.",
                "data_sources": ["io_write_bytes_per_sec", "io_read_bytes_per_sec"],
                "type": "line_graph",
                "columns": 5,
                "time_aggregation": {
                    "starting_value": "page_default",
                    "allow_selection": True,
                    "aggregation_function": "average_round"
                },
                "style": [
                    {
                        "lines_smooth": False,
                        "area_fill": True,
                        "label": "Write Bytes/sec",
                        "lines_color": 1
                    },
                    {
                        "lines_smooth": False,
                        "area_fill": True,
                        "label": "Read Bytes/sec",
                        "lines_color": 2
                    }],
                "time_range_filter": True
            },
            {
                "title": "Processes Count",
                "description": "A graph showing the number of processes over time.",
                "data_sources": ["processes_count"],
                "type": "line_graph",
                "columns": 9,
                "time_aggregation": {
                    "starting_value": "page_default",
                    "allow_selection": True,
                    "aggregation_function": "max"
                },
                "style": {
                    "lines_smooth": False,
                    "lines_color": 3
                },
                "time_range_filter": True
            },
            {
                "title": "Avg Processes Count",
                "description": "",
                "data_sources": ["processes_count"],
                "type": "counter",
                "counter_type": "average_round",
                "columns": 3,
                "height": 0.2,
                "time_range_filter": True
            },
            {
                "title": "Min Processes Count",
                "description": "",
                "data_sources": ["processes_count"],
                "type": "counter",
                "counter_type": "min",
                "columns": 0,
                "height": 0.2,
                "time_range_filter": True
            },
            {
                "title": "Max Processes Count",
                "description": "",
                "data_sources": ["processes_count"],
                "type": "counter",
                "counter_type": "max",
                "columns": 0,
                "height": 0.2,
                "time_range_filter": True
            },
            {
                "title": "Memory Usage - MB",
                "description": "A graph showing the memory usage, in MB, over time.",
                "data_sources": ["memory_usage_mb"],
                "type": "line_graph",
                "columns": 6,
                "values_suffix": " MB",
                "time_aggregation": {
                    "starting_value": "page_default",
                    "allow_selection": True,
                    "aggregation_function": "average_round"
                },
                "style": {
                    "lines_smooth": False,
                    "area_fill": True,
                    "label": "Mem Usage",
                    "lines_color": 4,
                },
                "time_range_filter": True
            },
            {
                "title": "Memory Usage - Percent",
                "description": "A graph showing the memory usage, in percent, over time.",
                "data_sources": ["memory_usage_percent"],
                "type": "line_graph",
                "columns": 6,
                "values_suffix": "%",
                "time_aggregation": {
                    "starting_value": "page_default",
                    "allow_selection": True,
                    "aggregation_function": "average_round"
                },
                "style": {
                    "lines_smooth": False,
                    "area_fill": True,
                    "label": "Mem Usage",
                    "lines_color": 4,
                    "markline": { "value_y": 80, "style": "dashed", "color": "red", "label": "" }
                },
                "time_range_filter": True
            },
            {
                "title": "Network Usage - Bytes Sent / Received per second",
                "description": "A graph showing the network usage (bytes sent / received per second) over time.",
                "data_sources": ["network_usage_bytes_sent", "network_usage_bytes_recv"],
                "type": "line_graph",
                "columns": 9,
                "time_aggregation": {
                    "starting_value": "page_default",
                    "allow_selection": True,
                    "aggregation_function": "average_round"
                },
                "style": [
                    {
                        "lines_smooth": False,
                        "area_fill": True,
                        "label": "Sent Bytes/sec",
                        "lines_color": 1
                    },
                    {
                        "lines_smooth": False,
                        "area_fill": True,
                        "label": "Received Bytes/sec",
                        "lines_color": 2
                    }],
                "time_range_filter": True
            },
            {
                "title": "Network Usage Distribution",
                "description": "A Donut chart showing the distribution of network traffic between sent and received bytes.",
                "data_sources": ["network_usage_bytes_sent", "network_usage_bytes_recv"],
                "type": "pie_chart",
                "columns": 3,
                "height": 0.8,
                "style": {
                    "aggregation_type": "sum",
                    "radius": "70%",
                    "show_legend": True,
                    "labels": ["Bytes Sent", "Bytes Received"],
                    "legend_position": "bottom",
                    "legend_orient": "horizontal",
                    "colors": ["#dc3545", "#198754"],
                    "label_formatter": "{b}: {d}%",
                    "border_width": 2,
                    "border_color": "#fff"
                },
                "time_range_filter": True
            },
            {
                "title": "Disk Usage - MB",
                "description": "A graph showing the disk usage, in MB, over time.",
                "data_sources": ["disk_usage_mb"],
                "type": "line_graph",
                "columns": 6,
                "values_suffix": " MB",
                "time_aggregation": {
                    "starting_value": "page_default",
                    "allow_selection": True,
                    "aggregation_function": "average_round"
                },
                "style": {
                    "lines_smooth": False,
                    "area_fill": True,
                    "label": "Disk Usage",
                    "lines_color": 5,
                },
                "time_range_filter": True
            },
            {
                "title": "Disk Usage - Percent",
                "description": "A graph showing the disk usage, in percent, over time.",
                "data_sources": ["disk_usage_percent"],
                "type": "line_graph",
                "columns": 6,
                "values_suffix": "%",
                "time_aggregation": {
                    "starting_value": "page_default",
                    "allow_selection": True,
                    "aggregation_function": "average_round"
                },
                "style": {
                    "lines_smooth": False,
                    "area_fill": True,
                    "lines_color": 5,
                    "markline": { "value_y": 80, "style": "dashed", "color": "red", "label": "" }
                },
                "time_range_filter": True
            }
        ]
    }
)

# windows-specific views if on Windows platform
import platform
if platform.system() == "Windows":
    VIEWS.append(
        {
            "id": "windows_counters", 
            "title": "Windows Performance Counters",
            "icon": "calc",
            "long_description": "Show some interesting Windows performance counters.",
            "inline_description": "Windows performance counters.", 
            "show_page_time_aggregation_selection": False,
            "data": [
                {
                    "id": "perf_counters", 
                    "event": "perf_counters", 
                    "last_unique_by_tag": True,
                    "tags": None
                }
            ],
            "widgets": [
                {
                    "title": "Windows Performance Counters",
                    "description": "A table showing Windows performance counters.",
                    "data_sources": ["perf_counters"],
                    "type": "table",
                    "max_rows": 100,
                    "height": 0,
                    "table_columns": [
                        { "title": "Counter Name", "event_field": "tag" },
                        { "title": "Value", "event_field": "value" },
                        { "title": "Last Update", "event_field": "time" }
                    ],
                    "time_range_filter": True
                }
            ]
        }
    )


# logs dashboard view
VIEWS.append(
    {
        "id": "logs", 
        "title": "Application logs",
        "icon": "doc",
        "long_description": "Show application logs. Note: this is just an example dashboard, so the logs we read are the Dashium application logs. Configure the config_data_collectors.py to extract your own logs.",
        "inline_description": "Application logs & errors / warnings graph.",
        "show_page_time_aggregation_selection": False,
        "data": [
            {
                "id": "log_message",
                "event": "log_message",
                "max_results": 15000,
                "max_age_days": 30,
                "tags": None
            }
        ],
        "widgets": [
            {
                "type": "bar_graph",
                "title": "Error & Warning Logs Over Time",
                "description": "Bar chart showing error and warning logs over time",
                "columns": 9,
                "height": 1,
                "show_no_data_message": False,
                "data_sources": [{"id": "log_message", "tags": ["WARNING"]}, {"id": "log_message", "tags": ["ERROR"]}, {"id": "log_message", "tags": ["CRITICAL"]}],
                "style": [
                    {
                        "bar_color": "warning",
                        "bar_width": "30%",
                        "label": "Warnings",
                        "border_radius": 4
                    },
                    {
                        "bar_color": "danger",
                        "bar_width": "30%",
                        "label": "Errors",
                        "border_radius": 4
                    },
                    {
                        "bar_color": "special",
                        "bar_width": "30%",
                        "label": "Criticals",
                        "border_radius": 4
                    }
                ],
                "time_aggregation": {
                    "starting_value": "day",
                    "allow_selection": True,
                    "aggregation_function": "sum",
                    "choices": ["10m", "30m", "hour", "day", "week"]
                }
            },
            {
                "title": "Log Types Distribution",
                "description": "A pie chart showing the distribution of log types.",
                "data_sources": [{"id": "log_message", "tags": ["INFO", "DEBUG"]},
                                 {"id": "log_message", "tags": ["WARNING"]},
                                 {"id": "log_message", "tags": ["ERROR"]},
                                 {"id": "log_message", "tags": ["CRITICAL"]}],
                "type": "pie_chart",
                "columns": 3,
                "height": 1,
                "style": {
                    "donut": True,
                    "show_center_text": True,
                    "center_text_formatter": "{total} Messages",
                    "center_text_size": 16,
                    "aggregation_type": "sum",
                    "radius": "70%",
                    "show_legend": True,
                    "labels": ["Info / Debug", "Warning", "Error", "Critical"],
                    "legend_position": "bottom",
                    "legend_orient": "horizontal",
                    "colors": ["primary", "warning", "danger", "special"],
                    "label_formatter": "{b}: {d}%",
                    "border_width": 2,
                    "border_color": "#fff"
                },
                "time_range_filter": True
            },
            {
                "title": "Application Logs",
                "description": "A table showing last 1000 application logs.",
                "data_sources": ["log_message"],
                "type": "table",
                "max_rows": 1000,
                "slice_from": "end",
                "height": 0,
                "filters": [
                    { "field": "Severity" }
                ],
                "table_columns": [
                    { "title": "#", "event_field": "index" },
                    { "title": "Severity", "event_field": "tag" },
                    { "title": "Message", "event_field": "additional_info" },
                    { "title": "Time", "event_field": "time" }
                ],
                "color_rules": [
                    { "event_field": "tag", "condition": "equals", "value": "DEBUG", "color": "secondary" },
                    { "event_field": "tag", "condition": "equals", "value": "WARNING", "color": "warning" },
                    { "event_field": "tag", "condition": "equals", "value": "ERROR", "color": "danger" },
                    { "event_field": "tag", "condition": "equals", "value": "CRITICAL", "color": "danger fw-bold" },
                ],
                "time_range_filter": True
            }
        ]
    }
)